config_cls: S2ProPipelineConfig
model_path: /data/xiedong/fishaudio/s2-pro
entry_stage: preprocessing
stages:
  - name: preprocessing
    executor:
      factory: sglang_omni.models.fishaudio_s2_pro.pipeline.stages.create_preprocessing_executor
      args: {}
    get_next: sglang_omni.models.fishaudio_s2_pro.pipeline.next_stage.preprocessing_next
    input_handler:
      type: direct
    relay:
      slot_size_mb: 512
      credits: 2
      device: cpu
    num_workers: 1
    stream_to: []
  - name: tts_engine
    executor:
      factory: sglang_omni.models.fishaudio_s2_pro.pipeline.stages.create_sglang_tts_engine_executor
      args:
        device: cuda:0
        max_new_tokens: 2048
        stream_vocoder_device: cpu
    get_next: sglang_omni.models.fishaudio_s2_pro.pipeline.next_stage.tts_engine_next
    input_handler:
      type: direct
    relay:
      slot_size_mb: 512
      credits: 2
      device: cuda
    num_workers: 1
    stream_to: []
  - name: vocoder
    executor:
      factory: sglang_omni.models.fishaudio_s2_pro.pipeline.stages.create_vocoder_executor
      args:
        device: cpu
    get_next: sglang_omni.models.fishaudio_s2_pro.pipeline.next_stage.vocoder_next
    input_handler:
      type: direct
    relay:
      slot_size_mb: 512
      credits: 2
      device: cpu
    num_workers: 1
    stream_to: []
name: s2pro-3090
terminal_stages: []
relay_backend: shm
fused_stages: []
endpoints:
  scheme: ipc
  base_path: /tmp/sglang_omni
  base_port: 16000
gpu_placement: {}
completion_endpoint: null
abort_endpoint: null
